<?php 
session_start();
include 'connection.php'; 

// Include PHPSpreadsheet library
require 'vendor/autoload.php';

// Use the classes
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Create new Spreadsheet object
$spreadsheet = new Spreadsheet();

// Set document properties
$spreadsheet->getProperties()->setCreator("Your Name")
                             ->setLastModifiedBy("Your Name")
                             ->setTitle("Attendance Report")
                             ->setSubject("Attendance")
                             ->setDescription("Attendance report generated by PHPSpreadsheet.")
                             ->setKeywords("attendance phpspreadsheet")
                             ->setCategory("Attendance");

// Set column headers
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Student ID')
      ->setCellValue('B1', 'Date')
      ->setCellValue('C1', 'Status');

// Fetch attendance records from database
$attendance_query = "SELECT Student_ID, Lecture_Date, Status FROM csd801_attendance";
$attendance_result = mysqli_query($conn, $attendance_query);

// Start from second row
$row = 2;

// Loop through each attendance record and add to Excel sheet
while ($row_data = mysqli_fetch_assoc($attendance_result)) {
    $sheet->setCellValue('A' . $row, $row_data['Student_ID'])
          ->setCellValue('B' . $row, $row_data['Lecture_Date'])
          ->setCellValue('C' . $row, $row_data['Status']);
    $row++;
}

// Rename worksheet
$sheet->setTitle('Attendance');

// Redirect output to a client’s web browser (Excel2007)
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="attendance_report.xlsx"');
header('Cache-Control: max-age=0');

// Create Excel file
$writer = new Xlsx($spreadsheet);
$writer->save('php://output');

exit;
?>